app/users/forms.py
#coding:utf-8

from flask_wtf import Form
from wtforms import StringField, PasswordField, BooleanField, SubmitField, IntegerField
from wtforms.validators import Required, Length, Email, Regexp, EqualTo,DataRequired
from wtforms import ValidationError
from ..models import User

class Email_RegistrationForm(Form):
    email = StringField(u'电子邮箱', validators=[DataRequired(), Length(1,64), Email()])
    username = StringField(u'用户名', validators=[
        DataRequired(),
        Length(1,64),
        Regexp('^[A-Za-z0-9_.]*$', 0,
               u'用户名必须为字母， '
               u'数字，点或者下划线')
    ])
    password = PasswordField(u'密码', validators=[
        Required(), EqualTo('password2', message=u'密码不匹配')])
    password2 = PasswordField(u'密码确认', validators=[Required()])
    submit = SubmitField(u'注册')

    def validate_email(self, field):
        if User.query.filter_by(email = field.data).first():
            raise ValidationError(u'该邮箱已经被使用')

    def validate_username(self, field):
        if User.query.filter_by(username = field.data).first():
            raise ValidationError(u'该用户名已经被使用')

class Phone_RegistrationForm(Form):
    phone = StringField(u'电话', validators=[DataRequired(), Length(1,64)])
    validate_code = IntegerField(u'验证码', validators=[DataRequired()])
    password = PasswordField(u'密码', validators=[
        DataRequired(), EqualTo('password2', message=u'密码不匹配')])
    password2 = PasswordField(u'密码确认', validators=[DataRequired()])
    submit = SubmitField(u'注册')

    def validate_email(self, field):
        if User.query.filter_by(phone = field.data).first():
            raise ValidationError(u'该电话已经被使用')


class LoginForm(Form):
    login_name = StringField(u'用户名', validators=[DataRequired(), Length(1,64)])
    passowrd = PasswordField(u'密码', validators=[DataRequired()])
    remember_me = BooleanField(u'保持登陆')
    submit = SubmitField(u'登录')

app/users/__init__.py
from flask import Blueprint

users = Blueprint('users', __name__)

from . import views

app/users/views.py
#coding:utf-8

import random
from . import users
from flask import render_template, flash, redirect, url_for, request, session, jsonify
from forms import Email_RegistrationForm, Phone_RegistrationForm,LoginForm
from flask_login import login_user, logout_user, login_required, current_user,current_app
from ..models import User
from .. import db
from sqlalchemy.sql import or_
from ..email import send_email
from ..phone import send_sms

@users.route('/')
def index():
    return render_template("base.html")

@users.route('/email-register', methods=['GET', 'POST'])
def email_register():
    form = Email_RegistrationForm()
    if form.validate_on_submit():
        user = User(email=form.email.data,
                        username=form.username.data,
                        password=form.password.data
                        )
        db.session.add(user)
        db.session.commit()
        # 得到令牌
        token = user.generate_confirmation_token()
        send_email(user.email, 'Confirm', '/user/email/confirm', user=user, token=token)
        flash(u'邮件已经发送致你的邮箱，若未收到，请注意查看你的邮件垃圾箱')
        return redirect(url_for('users.login'))
    return render_template("user/email_register.html", form = form)

@users.route('/phone-register', methods=['GET', 'POST'])
def phone_register():
    form = Phone_RegistrationForm()
    if form.validate_on_submit():
        if session['code'] == form.validate_code.data:
            user = User(phone=form.phone.data,
                            password=form.password.data
                            )
            user.confirmed = True
            db.session.add(user)
            db.session.commit()
            flash(u'手机验证成功')
            return redirect(url_for('users.login'))
    return render_template("user/phone_register.html", form = form)

@users.route('/phone-register-code')
def phone_register_code():
    # 随机生成 6位数 code
    if request.args.get('phone') is not None:
        code = random.randint(100000, 999999)
        session['code'] = code
        text = "【少寨主lucat】监控：验证码为%s" % code
        phone = request.args.get('phone')
        #调用短信接口发送
        if current_app.config['PHONE_API_KEY'] is not None:
            send_sms(current_app.config['PHONE_API_KEY'], text, phone)
            return jsonify({'phone': phone})
        return  jsonify({'phone':'false 1'})
    return jsonify({'phone': 'false 2'})

@users.route('/login', methods = ['GET','POST'])
def login():
    form = LoginForm()
    if form.validate_on_submit():
        # user = User.query.filter_by(email = form.email.data).first()
        user = User.query.filter(or_(User.username == form.login_name.data, User.phone == form.login_name.data ,User.email == form.login_name.data)).first()
        if user is not None and user.verify_password(form.passowrd.data):
            login_user(user)
            return redirect(request.args.get('next') or url_for('main.index'))
    return render_template('login.html', form = form)

@users.route('/logout')
def logout():
    logout_user()
    return redirect(url_for('main.index'))

@users.route('/confirm/<token>')
@login_required
def confirm(token):
    if current_user.confirmed:
        flash(u'你已经通过了验证,请不要重复')
        return redirect(url_for('main.index'))
    if current_user.confirm(token):
        flash(u'你已经通过了验证')
    else:
        flash(u'验证失败，请确认链接无误')
    return redirect(url_for('main.index'))

app/templates/_macros.html
{% macro pagination_widget(pagination, endpoint) %}
<ul class="pagination">
    <li{% if not pagination.has_prev %} class="disabled"{% endif %}>
        <a href="{% if pagination.has_prev %}{{ url_for(endpoint,
           page = pagination.page - 1, **kwargs) }}{% else %}#{% endif %}">
           &laquo;
        </a>
    </li>
    {% for p in pagination.iter_pages() %}
        {% if p %}
            {% if p == pagination.page %}
            <li class="active">
                <a href="{{ url_for(endpoint, page = p, **kwargs) }}">{{ p }}</a>
            </li>
            {% else %}
            <li>
                <a href="{{ url_for(endpoint, page = p, **kwargs) }}">{{ p }}</a>
            </li>
            {% endif%}
        {% else %}
            <li class="disabled">
                <a href="#">&hellip;</a>
            </li>
        {% endif %}
    {% endfor %}
    <li{% if not pagination.has_next %} class="disabled"{% endif %}>
        <a href="{% if pagination.has_next %}{{ url_for(endpoint,
            page = pagination.page + 1, **kwargs) }}{% else %}#{% endif %}">
            &raquo;
        </a>
    </li>
</ul>
{% endmacro %}

app/templates/base.html
<!DOCTYPE html>
<html lang="zh-cn" dir="ltr">
{% block head %}
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}我的博客 {% endblock %}</title>
    <link rel="shortcut icon" href="{{ url_for('static', filename = 'favicon.ico') }}" type="image/x-icon">
    <link rel="icon" href="{{ url_for('static', filename = 'favicon.ico') }}" type="image/x-icon">
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/default.css') }}">
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/technology.css') }}">
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/placeholderTypewriter.css') }}">

    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='edit/css/editormd.min.css') }}">
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='edit/css/editormd.logo.min.css') }}">
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='edit/css/editormd.preview.min.css') }}">

    <!-- css -->
    <link type="text/css" rel="stylesheet" href="http://cdn.bootcss.com/bootstrap/3.3.6/css/bootstrap-theme.min.css">
    <link type="text/css" rel="stylesheet" href="http://cdn.bootcss.com/bootstrap/3.3.6/css/bootstrap.min.css">
    <link type="text/css" rel="stylesheet" href="http://cdn.bootcss.com/font-awesome/4.6.1/css/font-awesome.min.css">
    <link type="text/css" rel="stylesheet" href="http://cdn.bootcss.com/font-awesome/4.6.1/fonts/fontawesome-webfont.svg">

    <!-- sweetalert 的 css -->
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='sweetAlert/css/sweet-alert.css') }}">
{#    <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.7/css/materialize.min.css">#}

    {% block style %}
        <style>

    .paper {
      background-color: #fffeff;
      width: 100px;
      height: 50px;
      overflow: hidden;
      position: relative;
      margin-bottom: 16px;
      box-shadow: 0px 1px 2px 1px #d3d2d3;
      border-radius: 2px;

      transition: 0.1s ease-in;
      -webkit-user-select: none;
      -moz-user-select: none;
      -ms-user-select: none;
      user-select: none;
    }

    .paper:hover {
      cursor: pointer;
    }


    .ripple {
      background-color: rgba(0, 0, 0, 0.45);
      border-radius: 100%;
      height: 100px;
      width: 50px;
{#      margin-top: -4px;#}
      position: relative;
      -webkit-transform: scale(0);
      transform: scale(0);
    }
    .animate {
      -webkit-animation: ripple 0.4s linear;
      animation: ripple 0.4s linear;
    }
    @-webkit-keyframes ripple {
      100% {
        -webkit-transform: scale(12);
        transform: scale(12);
        background-color: transparent;
      }
    }
    @keyframes ripple {
      100% {
        -webkit-transform: scale(12);
        transform: scale(12);
        background-color: transparent;
      }
    }
        </style>
    {% endblock %}

</head>
{% endblock %}

<body>

<div class="web-navbar">
{% block navbar %}
    <nav id="web-navbar-left" class="navbar nav-stacked navbar-default g-navbar-box " >
         <div class="navbar-header">
            <a href="{{ url_for('main.index') }}" target="_self" title="" class="navbar-brand" style="font-size: 14px;">我的博客</a>
        </div>
        <div class="">
            <ul id="" class="nav navbar-nav">
                <li class="menu-item">
                    <a target="_self" href="{{ url_for('main.index') }}" class="menu-item-link">网站首页</a>
                </li>
                <li class="menu-item">
                    <a target="_self" href="{{ url_for('main.about_me') }}" class="menu-item-link">关于博主</a>
                </li>
                <li class="menu-item">
                    <a target="_self" href="{{ url_for('main.technology') }}" class="menu-item-link">技术文章</a>
                </li>
                <li class="menu-item"><a  target="_self" href="{{ url_for('main.shares') }}" class="menu-item-link">资源分享</a>
                </li>
                <li class="menu-item"><a target="_self" href="{{ url_for('main.links') }}" class="menu-item-link">友情链接</a></li>
                <li class="menu-item"><a target="_self" href="{{ url_for('main.give_me_msg') }}" class="menu-item-link">给我留言</a></li>
                {% if current_user.is_authenticated %}
                    <li class="menu-item">
                        <a target="_self" href="{{ url_for('main.write_article') }}" class="menu-item-link">发表文章</a>
                    </li>
                    <li class="menu-item ">
                            <a href="{{ url_for('main.user', username = current_user.username) }}" class="menu-item-link">个人中心</a>
                    </li>
                {% endif %}
            </ul></div>
        <ul class="nav navbar-nav navbar-right">
        </ul>
    </nav>
{% endblock %}

{% block navbar_picture %}
{#    <div class="web-pic-box" id="web-pic-box" style="background-image: url('http://ocq1wrup5.bkt.clouddn.com/1.jpg');">#}
{#        <img src="" alt="">#}
{#            <div class="pic-box-font">#}
{#            <h3>新年寄语</h3>#}
{#            <p>潜心磨剑,藏器于身</p>#}
{#        </div>#}
{#    </div>#}
{% endblock %}

</div>

{% block show_article %}

{% endblock %}

{% block content %}
    <div class="web-content web-content-before" id="web-content">
        <div class='col-md-12 col-sm-12' style="padding-left: 4px;">
            {% for message in get_flashed_messages() %}
            <div class="alert alert-warning">
                <button type="button" class="close" data-dismiss="alert">&times;</button>
                {{ message }}
            </div>
            {% endfor %}
        {% block page_content %}{% endblock %}
        </div>
    </div>
    {% block write_article %}{% endblock %}
{% endblock %}


{% block script %}
     <!-- js -->
    <script src="http://cdn.bootcss.com/jquery/2.2.4/jquery.min.js" type="text/javascript"></script>
    <script src="http://cdn.bootcss.com/bootstrap/3.3.6/js/bootstrap.min.js" type="text/javascript"></script>
{#    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.7/js/materialize.min.js" type="text/javascript"></script>#}

    <!-- sweetalert -->
    <script src="{{ url_for('static', filename='sweetAlert/js/sweet-alert.js') }}"></script>
    <script src="{{ url_for('static', filename='js/placeholderTypewriter.js') }}"></script>

    <script type="text/javascript">
        $(function () {
            $("#web-pic-box").addClass("nav-after");
            $("#web-content").removeClass("web-content-before");
            $("#web-content").addClass("web-content-after");
        });
    </script>

{% endblock %}
</body>
</html>

app/templates/category.html
{% extends "base.html" %}

{% block title %} {{ category }} {% endblock %}

{% block style %}
    {{ super() }}
    <style>

    </style>
{% endblock %}

{% block page_content %}
    <div class="col-md-12" id="page_content" style="margin: 10px 0 0 0;">
        <span class="web-content-title" style="display: inline;"><span style="float: left">分类专题：{{ category }}</span>
            <form class="form-horizontal form-inline" style="display: inline; float: right" class="wrapper">
                <div class="form-group">
                    <input class="form-control" type="text" name="search" id="search">
                    <button class="btn btn-default"><i class="fa fa-search"></i></button>
                </div>
			</form>
        </span>
    </div>
    {%  for post in posts %}
        <div class="col-md-12 post-hover">
        <hr style="margin: 0px;padding: 10px 0 0 0;"/>
            <div class="web-article">
                <h2 class="post-title"><a style="color: #dd4814;" href="{{ url_for('main.show_article', id = post.id ) }}">{{ post.title }}</a></h2>
                <div class="meta-box">
                    <span class="m-post-date"><i class="fa fa-calendar"></i> &nbsp;{{ post.timestamp }}</span>
                    <span class="m-post-date"><i class="fa fa-user"></i> 作者：{{ post.author.username }}</span>
                    <span class="m-post-coments"><i class="fa fa-comments"></i> {{ posts_amount }} 条评论</span>
                </div>
                <div class="post-expect">
                    <p>{{ post.post_expect }}</p>
                </div>
                <div class="meta-box">
                    <span class="m-post-cat"><i class="fa fa-navicon"></i>
                        分类:{{ post.category }}
                    </span>
                    <span class="m-post-sorts"><i class="fa fa-tags"></i>标签:总结</span>
                </div>
            </div>
        </div>
    {% endfor %}
    <div id="get_article">

    </div>
    <div class="col-md-12" style="margin: 60px 0 20px;;">
        <div style="margin: 0 200px 0 200px;">
            <button class="btn btn-success" style="width: 100%" onclick="test();">
                <i class="fa fa-3x" id="icon-load"></i>
                <span class="fa fa-3x" style="font-size: 20px;padding: 11px 0 11px 0" id="btn-load">查看更多</span>
            </button>
        </div>

    </div>
    <div class="col-md-12" >
        <a target="_blank" href="" class="copyright-link">lucat博客 20013~2016 &copy; 站长邮箱:lucat369@gmail.com</a>
    </div>

{% endblock %}

{% block navbar_picture %}
    <div class="web-pic-box" id="web-pic-box" style="background-image: url('http://ocq1wrup5.bkt.clouddn.com/1.jpg');">
        <img src="" alt="">
            <div class="pic-box-font">
            <h3>新年寄语</h3>
            <p>潜心磨剑,藏器于身</p>
        </div>
    </div>
{% endblock %}

app/templates/default.html
{% extends "base.html" %}

{% block title %} hei {% endblock %}

app/templates/edit_article.html
{% extends "base.html" %}

{% block title %} 编辑文章 {% endblock %}

{% block script %}
    {{ super() }}

    <script src="{{ url_for('static', filename='edit/editormd.min.js') }}" type="text/javascript"></script>
    <script src="{{ url_for('static', filename='edit/code-block-dialog.js') }}" type="text/javascript"></script>
    <script src="{{ url_for('static', filename='edit/lib/flowchart.min.js') }}" type="text/javascript"></script>
    <script src="{{ url_for('static', filename='edit/lib/jquery.flowchart.min.js') }}" type="text/javascript"></script>
    <script src="{{ url_for('static', filename='edit/lib/prettify.min.js') }}" type="text/javascript"></script>
    <script src="{{ url_for('static', filename='edit/lib/raphael.min.js') }}" type="text/javascript"></script>
    <script src="{{ url_for('static', filename='edit/lib/sequence-diagram.min.js') }}" type="text/javascript"></script>
    <script src="{{ url_for('static', filename='edit/lib/underscore.min.js') }}" type="text/javascript"></script>
    <script src="{{ url_for('static', filename='edit/lib/marked.min.js') }}" type="text/javascript"></script>

    <script type="text/javascript">
    $(document).ready( function() {
        var editor = editormd("editormd", {
            path : "../static/edit/lib/" ,// Autoload modules mode, codemirror, marked... dependents libs path
            height : 640,
            theme : "dark",
            codeFold : true,
{#            syncScrolling : false,#}
{#            htmlDecode : "style,script,iframe|on*",            // 开启 HTML 标签解析，为了安全性，默认不开启#}
            emoji : true,
            taskList : true,
            tocm            : true,         // Using [TOCM]
            tex : true,                   // 开启科学公式TeX语言支持，默认关闭
            flowChart : true,             // 开启流程图支持，默认关闭
            sequenceDiagram : true,       // 开启时序/序列图支持，默认关闭,
            imageUpload : true,

        });
        editor.setToolbarAutoFixed(false);  // toolbar 自动调位 禁用

        $('#abc').click(function () {
            var msg = $('.editormd-preview').html()
{#            var msg = $("#cd").val()#}
            $('#body_html').val(msg)
        })
    })



</script>
{% endblock %}

{% block navbar_picture %}

{% endblock %}

{% block write_article %}
    {{ super() }}


{% if current_user.is_authenticated %}
      <div class="col-md-11" style="margin-bottom: 20px;margin-left: 100px;">
        <form action="/edit-article/{{ post.id }}" method="post" class="form-group">
            <div style="display: none">
                {{ form.csrf_token() }}
            </div>
            <div class="form-group">
                <label for="title">文章标题</label>
                  {{ form.title(id='title', class="form-control") }}
            </div>
            <div class="form-group" >
                <label for="editormd">文章内容</label>
                <div id="editormd">
                    {{ form.body(id='body') }}
                </div>
            </div>
             <div class="form-group">
                 {{ form.post_expect(id = 'post_expect', class='form-control', placeholder='文章摘要') }}
            </div>
             <div class="form-group" style="display: inline">
                {{ form.submit(id='abc', class='btn btn-default') }}
                 {{ form.category(id='catagory', class="btn btn-primary") }}
            </div>
            <div id="" style="display: none;">
                {{ form.body_html(id='body_html') }}
            </div>
        </form>
    </div>
{% endif %}
{#    <button id ='a' class="btn btn-default">点</button>#}

{% endblock %}

app/templates/give-me-msg.html
{% extends "base.html" %}

{% block title %} 给我留言 {% endblock %}

{% block style %}
    {{ super() }}
    <style>
        blockquote {
            background:#f9f9f9;
            border-left:3px solid #00d95a;
            line-height: 2.0em;
            font-size: 16px;
            margin: 0;
            padding:.5em 10px;
            quotes:"\201C""\201D""\2018""\2019";
        }

        blockquote p {
            display:inline;
        }
        .myimg {
            border: 2px solid #d28445;
            margin: 10px 0 10px 0;
            padding: 4px;
            width: 610px;
            height: 360px;
        }

        .msgcontent{
            margin-top: 20px;
            line-height: 2.5em;
            font-size: 15px;
        }

        #mybtn {
            font-size: 14px;
        }
    </style>
{% endblock %}

{% block page_content %}
    <div class="col-md-12" id="page_content" style="margin: 10px 0 0 0;">
        <span class="web-content-title" style="display: inline;"><span style="float: left"><h4 style="color: #A92733;">给我留言</h4></span>
        </span>
    </div>
    <div class="col-md-12" >
        <hr style="margin: 0px;padding: 10px 0 10px 0;"/>
        <h3 style="color: #A92733;">给我留言</h3>
        <blockquote>
            这里记录着我发现的，我思考的，我寻找的。<br/>
            很高兴和你成为朋友，关注生活，关注互联网。生活，远远比你想象的精彩。
        </blockquote>
        <img class="myimg" src="https://ws1.sinaimg.cn/large/005EFdvdgw1f88zx9nwevj30b4086wev.jpg" alt=""></br>
        <span class="msgcontent">
            如果你急于联系我，不妨给我写信。</br>
        </span>
        <button id="mybtn" onclick="show_email()" class="btn btn-default" style="background-color: #dd4814;color: white;"><i class="fa fa-envelope-o" aria-hidden="true"></i> 我的邮箱</button>
        &nbsp;&nbsp;
        <button id="mybtn" onclick="show_email()" class="btn btn-default" style="background-color: #dd4814;color: white;"><i class="fa fa-weibo" aria-hidden="true"></i> 我的微博</button>
        <span class="msgcontent">
            <br/>也可以在这留下你的足迹，留言内容，我会定期看到
        </span>
        <div class="ds-thread" data-thread-key="" data-title="留言" data-url="{{ url_for('main.give_me_msg') }}">

        </div>


    </div>
{% endblock %}

{% block navbar_picture %}
    <div class="web-pic-box" id="web-pic-box" style="background-image: url('https://ws2.sinaimg.cn/large/005EFdvdgw1f88zomidwtj306k09k0t9.jpg');">
        <img src="" alt="">
            <div class="pic-box-font">
            <h3>新年寄语</h3>
            <p>潜心磨剑,藏器于身</p>
        </div>
    </div>
{% endblock %}


{% block script %}
    {{ super() }}

    <!-- 多说公共JS代码 start (一个网页只需插入一次) -->
        <script type="text/javascript">
            var duoshuoQuery = {short_name:"lucat-369"};
            (function() {
                var ds = document.createElement('script');
                ds.type = 'text/javascript';ds.async = true;
                ds.src = (document.location.protocol == 'https:' ? 'https:' : 'http:') + '//static.duoshuo.com/embed.js';
                ds.charset = 'UTF-8';
                (document.getElementsByTagName('head')[0]
                 || document.getElementsByTagName('body')[0]).appendChild(ds);
            })();

            function show_email(){
                swal({
                        title: "",
                        text: "我的微博：",
                        confirmButtonText: "确定",
                        confirmButtonColor: "#ec6c62" ,
                        imageUrl: "{{ url_for('static', filename='sweetAlert/images/thumbs-up.jpg') }}"
                    });
            }
            </script>
        <!-- 多说公共JS代码 end -->

{% endblock %}

app/templates/login.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block title %} 登陆界面 {% endblock %}

{% block page_content %}
    {{ super() }}
    <div class="col-md-9">
        {{ wtf.quick_form(form) }}
    </div>
{#    <div class="col-md-2">#}
{#        <a href="{{ url_for('users.phone_register') }}" class="btn btn-default">注册</a>#}
{#    </div>#}
{% endblock %}

app/templates/post.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block title %} 文章发表{% endblock %}

{% block head %}
    {{ super() }}

    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='edit/css/editormd.min.css') }}">
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='edit/css/editormd.logo.min.css') }}">
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='edit/css/editormd.preview.min.css') }}">

    <script src="{{ url_for('static', filename='edit/editormd.min.js') }}" type="text/javascript"></script>
    <script src="{{ url_for('static', filename='edit/code-block-dialog.js') }}" type="text/javascript"></script>
    <script src="{{ url_for('static', filename='edit/lib/flowchart.min.js') }}" type="text/javascript"></script>
    <script src="{{ url_for('static', filename='edit/lib/jquery.flowchart.min.js') }}" type="text/javascript"></script>
    <script src="{{ url_for('static', filename='edit/lib/prettify.min.js') }}" type="text/javascript"></script>
    <script src="{{ url_for('static', filename='edit/lib/raphael.min.js') }}" type="text/javascript"></script>
    <script src="{{ url_for('static', filename='edit/lib/sequence-diagram.min.js') }}" type="text/javascript"></script>
    <script src="{{ url_for('static', filename='edit/lib/underscore.min.js') }}" type="text/javascript"></script>
    <script src="{{ url_for('static', filename='edit/lib/marked.min.js') }}" type="text/javascript"></script>

    <script type="text/javascript">
    $(document).ready( function() {
        var editor = editormd("editormd", {
            path : "../static/edit/lib/" ,// Autoload modules mode, codemirror, marked... dependents libs path
            height : 640,
            theme : "dark",
            codeFold : true,
            syncScrolling : false,
            htmlDecode : "style,script,iframe|on*",            // 开启 HTML 标签解析，为了安全性，默认不开启
            emoji : true,
            taskList : true,
            tocm            : true,         // Using [TOCM]
            tex : true,                   // 开启科学公式TeX语言支持，默认关闭
            flowChart : true,             // 开启流程图支持，默认关闭
            sequenceDiagram : true,       // 开启时序/序列图支持，默认关闭,
            imageUpload : true,

        });

        $('#bca').click(function () {
            var msg = $('.editormd-preview').html()
{#            var msg = $("#cd").val()#}
            alert(msg)
            $('#wei').html(msg)
        })

    })



</script>
{% endblock %}


{% block page_content %}
    {{ super() }}

        <div>
        {% if post != None %}
           <div class="" id="abcde">
                {{ post }}123
           </div>
        {% endif %}
    </div>
    <div id="wei">

    </div>

{#    <script>#}
{#        document.getElementById('wei').innerHTML = marked('```python    def index():    return "hello "```')#}
{#    </script>#}

    <div class="col-md-12" style="margin-bottom: 20px;">
        <form action="/post" method="post" class="form-group">
            <div style="display: none">
                {{ form.csrf_token() }}
            </div>
            <div class="form-group">
                <label for="title">文章标题</label>
                  {{ form.title(id='title', class="form-control") }}
            </div>
            <div class="form-group" >
                <label for="editormd">文章内容</label>
                <div id="editormd">
                    {{ form.body(id='body', class="editormd-markdown-textarea") }}
                </div>
            </div>
             <div class="form-group" style="display: block">
                {{ form.submit(id='abc', class='btn btn-default') }}
            </div>
        </form>
        <button class="btn btn-default" id="bca">点点</button>
    </div>



{#    <button id ='a' class="btn btn-default">点</button>#}
{##}

{% endblock %}

app/templates/test.html
<p>{{ name }}</p>

app/templates/user.html
{% extends "base.html" %}

{% block title %} 用户主页 {% endblock %}